### ISSUE TITLE
Using other pre-trained models

### ISSUE THREAD

**Issue by Soebb** [zackees/pydeepspeech#1]
For now, can it be done if i replace [this list](https://github.com/zackees/pydeepspeech/blob/main/pydeepspeech/installModels.py#L14) with
`['https://itml.cl.indiana.edu/models/fa/output_graph.pbmm', 'https://itml.cl.indiana.edu/models/fa/kenlm.scorer']`
Or the code need to re-write to support?

Sorry that I'm newbie in deepspeech.

**Comment by zackees** [comment]
Yes, that should work. If it doesn't, post the error message and the url's you used and I'll fix it for you.

**Comment by zackees** [comment]
Hi there, this will do what you want it to do:
```
$ pydeepspeech --wav_file <WAVE_FILE> --out_file <TEXT_FILE> --model_dir <MY_PBMM_AND_SCORER_FILES>
```

**Comment by zackees** [comment]
might also want to do

`python -m pip install pydeepspeech --upgrade`

**Comment by Soebb** [comment]
Great update.
Thanks.
